### ISSUE TITLE
Clearer language in Readme?

### ISSUE THREAD

**Issue by rmflight** [aitap/nodepool#1]
So right now there is "pool server", "pool machine" , which I think are equivalent, and then there are "nodes" and "clients", and it's not 100% clear the relationship between them.

I **think** from the description that a "client" machine is where you have your task that you actually want to run, and it connects to and submits jobs to the pool. The pool server is managing everything.

For people used to cluster computing, these terms are probably second nature. But if you've not used a lot of cluster compute, then it's not easy to parse. A diagram, or a link to another resource (maybe the parallel package docs) would probably help a lot.

I like this idea, being able to setup a cluster where if a member dies or is taken offline then the job just gets resubmitted to another is really, really nice. Although the setup is a little harder than for `parallel::makeCluster`, it looks incredibly useful.

**Comment by aitap** [comment]
You're absolutely right, the words I'm using here could be improved,
and this could be our last chance to do that, before the terminology
and the API is set in stone. I've added a diagram that hopefully makes
it clear that "clients" submit tasks to the "pool" and that "nodes"
receive these tasks (to run them). I'll add more arrows later and maybe
separate the flow of "tasks" and their "results" (which is two-way) and
the network connections (which are always from other computers to the
"pool").

What could be a better way to call them? I thought of "workers" running
"jobs", but to my non-native-speaker ear this makes them sound too
human-like. I would prefer the nodes to stay the soulless computers
they are. The origins of the word "robot" could make it a good fit in
theory, but perhaps not given a century of connotations it has since
acquired.

**Comment by rmflight** [comment]
So I think pool, nodes, clients all are fine. And the new diagram clears it up a lot! But you switched from "pool server" to "pool machine", which made it a little confusing to follow. The pull request (#2 ) is just to make things a bit more consistent throughout, and add installation instructions.

**Comment by aitap** [comment]
I appreciate the pull request finding and fixing more problems. Thank
you!
